version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 12
      commands:
        - echo Installing npm dependencies
        - npm install -g npm@latest
        - npm -v
        - npm install
    build:
      commands:
        - echo Running tests with coverage report
        - npm audit
        - npm run coverage
artifacts:
    files:
      - '**/*'
