version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 12
      commands:
        - echo Installing npm dependencies
        - npm install -g npm@latest
        - npm -v
        - npm install
    build:
      commands:
        - echo Running tests with coverage report
        - npm audit
        - npm run coverage
    post_build:
      commands:
        - echo Detected commit hash $CODEBUILD_RESOLVED_SOURCE_VERSION
        - echo $CODEBUILD_RESOLVED_SOURCE_VERSION > release_version
artifacts:
    files:
      - '**/*'
